### ISSUE TITLE
XCM API should be able to process custom field calls

### ISSUE THREAD

**Issue by peth-systopia** [systopia/de.systopia.xcm#1]
Submitting values for custom fields does not seem to be implemented yet. Please implement. :-)

**Comment by systopia** [comment]
The extension works on a predefined set of attributes. This is needed for the "create an activity with the differences" to make sense. We shouldn't change this concept, so I suggest to add a setting option where you can individually select the custom fields that you want to be included in the matching/diff process.

**Comment by systopia** [comment]
@peth-systopia Is this still relevant?

**Comment by peth-systopia** [comment]
Not currently, but since it seems to be a feature that will probably become relevant at some point, maybe leave it open with "needs funding" tag?

**Comment by systopia** [comment]
Ok.

**Comment by systopia** [comment]
@peth-systopia Does this work in the ``1.5.alpha1``?

**Comment by jensschuppe** [comment]
This is quite old, and I don't get what it's about. Is this still relevant, @bjendres?

**Comment by bjendres** [comment]
assuming this works with at least ``1.5``, please re-open if that's wrong
