### ISSUE TITLE
Current master branch not compatible with CiviCRM versions > 5.60

### ISSUE THREAD

**Issue by SiMaHer** [systopia/de.systopia.xcm#105]
In the current master branch you can find a usage of `CRM_Core_OptionGroup::getValue` in the file `CRM/Xcm/CustomData.php`. This is not the case for the latest release 1.10.0

**Comment by bjendres** [comment]
Hi @SiMaHer, thanks for reporting. I have updated some outdated calls in the code, see [here](https://github.com/systopia/de.systopia.xcm/tree/07d0985cd577357bb4ea5fd7484068bf29b70c18). Could see and verify if it works with that version? You can download it [here](https://github.com/systopia/de.systopia.xcm/archive/07d0985cd577357bb4ea5fd7484068bf29b70c18.zip).

**Comment by bjendres** [comment]
@SiMaHer: Any chance you could confirm that this branch works for you? See https://github.com/systopia/de.systopia.xcm/issues/105#issuecomment-1663843613
