### ISSUE TITLE
Error on non-existing elements when deleting activities

### ISSUE THREAD

**Issue by ErikHommel** [systopia/de.systopia.xcm#15]
When I try to delete an activity from the contact summary I get the error:

> #5 /var/www/html/aivldev/sites/all/modules/civicrm/packages/HTML/QuickForm.php(791): PEAR->raiseError(NULL, -3, NULL, 512, "Element 'status_id' does not exist in HTML_QuickForm::getElement()", "HTML_QuickForm_Error", TRUE)

I did include the try/catch block that was put around the getElements in a later version, but that does not fix the issue.

**Comment by systopia** [comment]
@ErikHommel: I would assume it's the "diff helper" which is marked as 'beta'. Does the problem persist if you turn it off (xcm configuration)?

**Comment by ErikHommel** [comment]
Could well be - but I did a PR with a fix too :-)

**Comment by systopia** [comment]
I've seen it, just wanted to verify that the diff helper was the cause

**Comment by ErikHommel** [comment]
I do not remember exactly but I can try to switch off my fix and then see if the problem persists.

**Comment by ErikHommel** [comment]
Yes, the cause is the diff helper. No problems if I switch it off.
