### ISSUE TITLE
Replace deprecated CRM_Core_OptionGroup::getValue()

### ISSUE THREAD

**Issue by ErikHommel** [systopia/de.systopia.xcm#20]
Throws warnings and shows up in CiviCRM log, replace with either API calls or CRM_Core_PseudoConstant

**Comment by jensschuppe** [comment]
@ErikHommel I think you meant `CRM_Core_OptionGroup::getValue()`?

Will take care of them before 1.5-beta1.

**Comment by jensschuppe** [comment]
@ErikHommel, @systopia Could you review f46b2de8f7ef985419afccee696c6597b5a02e69 and confirm that it solves the issue?
