### ISSUE TITLE
Enable multiple configurations as "profiles"

### ISSUE THREAD

**Issue by bjendres** [systopia/de.systopia.xcm#30]
Sometimes XCM is used for a variety of different scenarios and different data sources. It would be really good if we could not only have "one size fits all" configuration, but a number of them identified by name. This way, different scenarios could use different "profiles" with different configurations.

**Comment by jensschuppe** [comment]
Requirement details, as discussed with @systopia:
- Each profile has an alphanumeric name, which serves as the identifier
- A `default` profile always exists, and is used as a fallback when XCM is used without specifying a profile name
- An upgrader will migrate to the new configuration storage
- The API action `Contact.getorcreate` receives the profile name as an optional parameter (defaults to `default`)
- The configuration UI is being added a profile overview page, which redirects to the `default` profile configuration form, if no other profile exists
- A "New profile" button is added to the profile overview page and the `default` profile configuration form, if no other profile exists
- The profile overview page provides the option to clone an existing profile to a new one
- The various CiviCRM settings will be merged into one setting record in the database
- profile configuration forms are being validated to avoid profile name conflicts

**Comment by bjendres** [comment]
released with ``1.6``
