### ISSUE TITLE
Additional address created when contact matched via contact ID

### ISSUE THREAD

**Issue by jensschuppe** [systopia/de.systopia.xcm#35]
## Steps to reproduce
- Pick a contact with an address of location type "private"
- Configure XCM's default location type to be "private"
- Configure XCM to only add an Address record when the contact does not have one with the "private" location type
- Perform an API call to `Contact.getorcreate` with only the contact ID and some address data as parameters - i.e. no data that would result in a contact match using XCM's matching rules

## Expected result
- The contact has not changed, i.e. no new "private" address has been added

## Actual result
- The contact has a new additional "private" address record

## Technical background
Since the contact is not being matched using XCM's rules, `CRM_Xcm_MatchingEngine::createContact()` is being called, which issues a
```php
civicrm_api3('Address', 'create', $address_data);
```
without checking for existing addresses or any XCM settings at all.

## Proposed resolution
Instead of falling back to `CRM_Xcm_MatchingEngine::createContact()`, `CRM_Xcm_MatchingEngine::matchContact()` should always try to match the contact by contact ID if it was given.

Alternatively, some logic like in `CRM_Xcm_MatchingEngine::addDetailToContact()` could be implemented for address records.

**Comment by jensschuppe** [comment]
Planned implementation after discussing with @systopia:

Implement a configuration switch: accept contact ID as parameter or not
- if yes, match by contact ID first (exclude deleted contacts) and copy the parameter to "xcm_submitted_contact_id" and throw away the parameter
- if no, rename the parameter without matching.

Pay attention to feature parity with a contact ID matching rule.

Finding merged contacts (using ID tracker) will be a sub-feature to consider.

**Comment by systopia** [comment]
@jensschuppe Please create a new feature ticket, as discussed
