### ISSUE TITLE
Provide a defined way to match by contact ID

### ISSUE THREAD

**Issue by jensschuppe** [systopia/de.systopia.xcm#36]
Follow-up of #35:

Planned implementation after discussing with @systopia:

Implement a configuration switch: accept contact ID as parameter or not
- if yes, match by contact ID first (exclude deleted contacts), copy the parameter to e.g. `xcm_submitted_contact_id` and throw away the `id` parameter
- if no, rename the parameter without matching.

Pay attention to feature parity with a contact ID matching rule, which circumvents the problem described in #35.

Finding merged contacts (using ID tracker) will be a sub-feature to consider.

**Comment by jensschuppe** [comment]
@systopia Could you review 46c92d0cf9b7350664734fe240aedddc5850e25b?

**Comment by jensschuppe** [comment]
N.B. This needs a translation (template) and documentation update before merging/releasing.

**Comment by jensschuppe** [comment]
I should add that the commit does not take into account deleted contacts, since a dedupe rule for contact ID does not either and we'd want feature parity with that.

**Comment by jensschuppe** [comment]
As discussed with @systopia:

Deleted contacts should never be part of the matching result.

We should test whether other dedupe rules (e.g. email only) yield deleted contacts. If so, that's possibly a core bug.

**Comment by jensschuppe** [comment]
Just tested again a dedupe rule for contact ID only and can confirm it does *not* match deleted contacts. Don't know what made me think it would.

@systopia your improved implementation is thus behaving correctly.

**Comment by jensschuppe** [comment]
This got merged, thus closing the issue.

**Comment by jensschuppe** [comment]
This was using the old way of retrieving XCM options, instead of the new profiles. This is now fixed.

**Comment by bjendres** [comment]
released with ``1.6``
