### ISSUE TITLE
No parameters given to CRM_Utils_Number::formatUnitSize()

### ISSUE THREAD

**Issue by jensschuppe** [systopia/de.systopia.xcm#40]
1a1a8c47b0db71fb5c2d848b834057ca8bc51983 (as part of #30) introduced a copy of `CRM_Utils_Number::formatUnitSize()` which calls the core method if it exists, but without parameters, causing a PHP ArgumentCountError in PHP >= 7.1.

**Comment by bjendres** [comment]
released with ``1.6``
