### ISSUE TITLE
XCM should provide a (form processor) action

### ISSUE THREAD

**Issue by bjendres** [systopia/de.systopia.xcm#46]

**Comment by jensschuppe** [comment]
Array addition would not add extra fields to the parameter specification, since both arrays have numerical keys. Using `array_merge()` instead works in this case. I changed that in c1f00798f34fd8893cb43232b3112a604a389cf1.

**Comment by bjendres** [comment]
thanks

**Comment by jensschuppe** [comment]
There should be a check for the action class itself being existent, see https://github.com/Project60/org.project60.sepa/issues/554#issuecomment-564079096 for why and how.

**Comment by jensschuppe** [comment]
the form processor action does not provide an input parameter for the contact ID, but a parameter called `xcm_submitted_contact_id` instead. This is the internal parameter the submitted contact ID will be set to, but itÄs not used anywhere after matching by contact ID.

The dorm processor action should provide the `id` parameter.

**Comment by bjendres** [comment]
Released with ``1.7``
