### ISSUE TITLE
Contact Update Report

### ISSUE THREAD

**Issue by bjendres** [systopia/de.systopia.xcm#64]
You can make a good case for wanting to know what parts of your contact has been changed by XCM. Therefore, there should be an option to generate an activity with the actual changes applied to the contact, pretty much like the diff activity does for remaining differences.

**Comment by bjendres** [comment]
@jaapjansma is this what you had in mind with #62?

**Comment by jaapjansma** [comment]
yes but then per contact.

**Comment by bjendres** [comment]
> yes but then per contact.

Isn't this always 'per contact'?

**Comment by bjendres** [comment]
After talking to @jaapjansma, I believe his ![suggestion](https://user-images.githubusercontent.com/4126292/85139087-341c1f80-b244-11ea-8e02-1170b78a033f.png) makes sense, because this is the only way to have a mixed activity with applied *and* pending changes.

**Comment by jensschuppe** [comment]
Will updated and pending changes be distinguishable in the activity? Does it make sense to provide an "Update activity" as well (since that'd be the same code - just in case, someone wants that, too)?

I'd also vote for clear descriptions of what is being recorded with those options - there has been some confusion in the past, apparently.

**Comment by jaapjansma** [comment]
No the activity record the original data and the submitted data without indicating whether the changes have been applied or not. But that make sense probably in the context of the site user because it is also their configuration.

**Comment by bjendres** [comment]
Maybe we should find better labels for the two options. "Update and Difference Activity" sounds confusing compared to "Diff Activity". I would suggest:
* "Contact Value Comparison" (for all data, i.e. Jaap's new thing)
* "Unresolved Differences" (for the old feature)

There might also be a point in adding the "Activity Status" field in this context. ``Pending`` makes sense for the "Unresolved Differences", but if you use the "Contact Value Comparison" for documentation only, you might want ``Completed``...

Sorry for scope-creeping, @jaapjansma ...

**Comment by jaapjansma** [comment]
I have renamed the handlers. See PR #63

**Comment by jensschuppe** [comment]
Since we're in beta phase for 1.8, this will have to wait until 1.9.
