### ISSUE TITLE
No settings menu option?

### ISSUE THREAD

**Issue by MegaphoneJon** [systopia/de.systopia.xcm#65]
I just installed XCM (master branch) and it didn't create a navigation menu item for the Settings page, which it says in the docs it does.  I skimmed the code and saw where you're adding the "Import Contacts (XCM)" menu option, but that was it.

It seems like this would have been reported sooner if this was a bug; could you confirm that this menu is added on installation?

**Comment by bjendres** [comment]
I think you're right. There was a navigation menu link at one point, but I'd have to investigate what happened to it. However, there is (and has always been) an entry in the admin console (``civicrm/admin``) for configuration.

**Comment by jensschuppe** [comment]
Will be released with `1.8`

**Comment by bjendres** [comment]
released with ``1.8``
