### ISSUE TITLE
Filling custom fields not working any more with CiviCRM 5.27+

### ISSUE THREAD

**Issue by bjendres** [systopia/de.systopia.xcm#68]
It seem like a change in the handling of custom field types, there has been an internal change in CiviCRM ``5.27``. Multi-Value fields used to be marked by the ``html_type`` "Multi-Select" (and two more "Multi-*"). 

With ``5.27`` the ``html_type`` was always set to "Select" and the ``serialize`` flag was used to mark multi-value fields.

They have added some compatibility code to provide a legacy API (v3), but they didn't cater for ``html_type`` search parameters. Therefore XCM doesn't detect these fields as multi-value, and ignores them.

See [CORE-1996](https://lab.civicrm.org/dev/core/-/issues/1996)

**Comment by jensschuppe** [comment]
Will be released with `1.8`

**Comment by bjendres** [comment]
released with ``1.8``
