### ISSUE TITLE
Option to strip utf8mb4 characters

### ISSUE THREAD

**Issue by bjendres** [systopia/de.systopia.xcm#70]
Writing utf8mb4 values to the CiviCRM DB might cause a ``DB Error: unknown error``, crashing the XCM reconciliation process.

The suggestion is here, to add a configuration option (per profile) to simply strip those characters from the input data.

**Comment by pfigel** [comment]
@bjendres this might contain some useful snippets: https://github.com/greenpeace-cee/at.greenpeace.multibite

**Comment by bjendres** [comment]
[That](https://github.com/greenpeace-cee/at.greenpeace.multibite/blob/master/CRM/Multibite/Processor/AbstractProcessor.php) looks good, thank you!

**Comment by jensschuppe** [comment]
Will be released with `1.8`

**Comment by bjendres** [comment]
released with ``1.8``
