### ISSUE TITLE
Drop support for CiviCRM versions supporting PHP < 7.2

### ISSUE THREAD

**Issue by jensschuppe** [systopia/de.systopia.xcm#77]
... which is, according to [the docs](https://docs.civicrm.org/installation/en/latest/general/requirements/#php-version), versions lower than `5.14`.

We might want to go further and drop support for CiviCRM versions supporting PHP < `7.1` since the current ESR release is already marked incompatible with PHP `7.0`

@bjendres thoughts?

**Comment by bjendres** [comment]
@jensschuppe Is there a specific reason for it?

**Comment by bjendres** [comment]
Also, maybe we should schedule this for the next version (``1.9``)?

**Comment by jensschuppe** [comment]
Reason being to be able to adopt PHP 7 language constructs. Pushing to 1.9 seems ok to me, since it'd be an API break.

However, discussing whether to support EOL PHP 7 versions, seems appropriate to me. The latest CiviCRM ESR release is incompatible with PHP 7.0 already.

**Comment by jensschuppe** [comment]
3115564f2baf0004de15e6b45c3f8d6dca9acaeb drops support for CiviCRM Core versions supporting PHP < 7.2, so at least CiviCRM Core 5.35.0 is required. Dropping support for PHP 7.2 (by requiring CiviCRM Core 5.58) would introduce an incompatibility with the current ESR, which is 5.51.
