### ISSUE TITLE
Do not overwrite details with empty values

### ISSUE THREAD

**Issue by MarcMichalsky** [systopia/de.systopia.xcm#78]
Hello,

we recently faced the problem that existing address data were removed when the "Change Primary Detail?" option was checked. This happens if we receive a donation via TwingleDonation.submit that does not contain any address information.

I am not sure if this behaviour is intended or not, but it is kind of counterintuitive. I would expect the XCM to overwrite data only with new data.

This is our XCM config:
![XCM_config](https://user-images.githubusercontent.com/24728186/109283745-6e03e380-781f-11eb-8d97-1e0c51faeb5b.png)

**Comment by bjendres** [comment]
@MarcMichalsky Are you sure that all of [these attributes](https://github.com/systopia/de.systopia.xcm/blob/15da3be31053e444cf3dab36e08ed0247a80649f/CRM/Xcm/MatchingEngine.php#L827-L831) were empty in your incoming data? If so, it shouldn't have done anything, see [here](https://github.com/systopia/de.systopia.xcm/blob/15da3be31053e444cf3dab36e08ed0247a80649f/CRM/Xcm/MatchingEngine.php#L838-L848).

**Comment by MarcMichalsky** [comment]
I tested it again with this json in the call:
```json
{"project_id":"tw5f64adce40693","trx_id":"foobar5","parent_trx_id":null,"confirmed_at":20210226110000,"purpose":"Allgemeine Spende","amount":2800,"currency":"EUR","user_email":"m.michalsky@posteo.de","user_country":"DE","user_language":"de","payment_method":"paypal","donation_rhythm":"one_time","is_anonymous":0,"newsletter":1,"postinfo":0,"donation_receipt":1,"user_gender":"male","user_title":null,"user_firstname":"Marc","user_lastname":"Michalsky", "custom_fields":{}}
```

My address data got removed.

**Comment by MarcMichalsky** [comment]
Oh, wait, the country remains what means that the `country_id` attribute was filled anywhere. I will have a closer look into this later. Maybe this Issue belongs to the de.systopia.twingle repository.

**Comment by bjendres** [comment]
@MarcMichalsky should I flag this as invalid, then?

**Comment by MarcMichalsky** [comment]
> @MarcMichalsky should I flag this as invalid, then?

I think it's invalid here, in the XCM-Repro, because there is nothing wrong about how the XCM treats this. But I think other de.systopia.twingle users could run into the same problem, because the country is always transmitted along with a PayPal donation. Maybe we should mention it in the [XCM section of the de.systopia.twingle documentation](https://github.com/systopia/de.systopia.twingle#configure-extended-contact-matcher-xcm). I'll maybe send a PR there.
Thank you so far!

**Comment by bjendres** [comment]
Thanks to you for raising it. Now we have it documented for the next person to come along...
