### ISSUE TITLE
Difference Handling does not work

### ISSUE THREAD

**Issue by mariav0** [systopia/de.systopia.xcm#92]
Hi there,
I am not sure if something in my configuration is wrong but my colleague and me were trying a lot of different options and we can not make it work.
This is my current config:

![image](https://user-images.githubusercontent.com/70949178/164431594-a513e891-8193-4d35-a948-8381834997ba.png)

![image](https://user-images.githubusercontent.com/70949178/164431417-e6394ce5-9520-4779-9661-800192d30b9d.png)

Is there anything wrong why it does not create an activity?
Tested on 5.47.4 + XCM 1.9-alpha6 and 1.8

**Comment by AHowiller** [comment]
Hi @mariav0, I also found this confusing but this seems to be intended behavior as discussed in #63 and #64 – this PR by @jaapjansma should meet your requirements. Maybe this issue can just be closed in favor of these two?

**Comment by mariav0** [comment]
Thanks, I'll test this soon!
