### ISSUE TITLE
PHP 8.0 Compatibility

### ISSUE THREAD

**Issue by abugey** [systopia/de.systopia.xcm#98]
* [x] Analyse code regarding PHP 8 compatibility
* [x] Fix deprecations found (to be specified)

**Comment by abugey** [comment]
Error in PHP 8.0: 
`CustomData.php: Ilegal array key type in lines 708, 709, 730, 732, 735: [$field_id]`

**Comment by eptbertram** [comment]
Error in PHP7.4: 
User deprecated function: Attributes passed to CRM_Core_Form::add() are not an array. Caller: CRM_Xcm_Form_Import::buildQuickForm in CRM_Core_Error::deprecatedWarning() (line 1103 of /home/www/staging/project/src/drupal/vendor/civicrm/civicrm-core/CRM/Core/Error.php).
